// <auto-generated />
namespace PhanMemQuanLyKhachSan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class AddTrangThaiToPhong : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTrangThaiToPhong));
        
        string IMigrationMetadata.Id
        {
            get { return "202505180124453_AddTrangThaiToPhong"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
